# Generated by Django 4.1.2 on 2023-05-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='remote_host',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='remote_user',
        ),
    ]
